[colors]
foreground = "#54433A"
background = "#F1F1F1"
cursor_bg = "#54433A"
cursor_border = "#54433A"
cursor_fg = "#F1F1F1"
selection_bg = "#D9D3CE"
selection_fg = "#54433A"
ansi = [
  "#E9E1DB",
  "#C77B8B",
  "#6E9B72",
  "#BC5C00",
  "#7892BD",
  "#BE79BB",
  "#739797",
  "#7D6658"
]
brights = [
  "#A98A78",
  "#BF0021",
  "#3A684A",
  "#A06D00",
  "#465AA4",
  "#904180",
  "#3D6568",
  "#54433A"
]
tab_bar = { background = "#D9D3CE", active_tab = { bg_color = "#54433A", fg_color = "#D9D3CE", intensity = "Bold" }, inactive_tab = { bg_color = "#D9D3CE", fg_color = "#54433A" }, new_tab = { fg_color = "#54433A", bg_color = "#D9D3CE" } }
